# Generated by Django 5.1.6 on 2025-02-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='tbl_contactos',
        ),
    ]
